package com.sxwl.dao;

import com.sxwl.entity.sysRoleUser;
import com.sxwl.entity.sysRoleUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    long countByExample(sysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByExample(sysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insert(sysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insertSelective(sysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    List<sysRoleUser> selectByExample(sysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    sysRoleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") sysRoleUser record, @Param("example") sysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExample(@Param("record") sysRoleUser record, @Param("example") sysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKeySelective(sysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKey(sysRoleUser record);
}