package com.sxwl.dao;

import com.sxwl.entity.sysRoleAcl;
import com.sxwl.entity.sysRoleAclExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysRoleAclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    long countByExample(sysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByExample(sysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insert(sysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insertSelective(sysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    List<sysRoleAcl> selectByExample(sysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    sysRoleAcl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") sysRoleAcl record, @Param("example") sysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExample(@Param("record") sysRoleAcl record, @Param("example") sysRoleAclExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKeySelective(sysRoleAcl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_acl
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKey(sysRoleAcl record);
}