package com.sxwl.dao;

import com.sxwl.entity.sysRole;
import com.sxwl.entity.sysRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    long countByExample(sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByExample(sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insert(sysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insertSelective(sysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    List<sysRole> selectByExample(sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    sysRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") sysRole record, @Param("example") sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExample(@Param("record") sysRole record, @Param("example") sysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKeySelective(sysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKey(sysRole record);
}