package com.sxwl.dao;

import com.sxwl.entity.sysUser;
import com.sxwl.entity.sysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface sysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    long countByExample(sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByExample(sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insert(sysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int insertSelective(sysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    List<sysUser> selectByExample(sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    sysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") sysUser record, @Param("example") sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByExample(@Param("record") sysUser record, @Param("example") sysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKeySelective(sysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Sat Aug 03 18:28:54 CST 2019
     */
    int updateByPrimaryKey(sysUser record);
}